In [0]:
#Artificial neural network
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
os.chdir('/content/drive/My Drive/Colab Notebooks/MLLab/lab')

9.Artificial Neural Network classification for the Business Problem: 
In the recent past six months, a leading bank in Europe having many branches in France, Germany and Spain, noticed that the customers left the bank. In order to predict the possibility of customers who may leave the bank in near future well in advance and address the issues, the bank has decided to go for an ANN based classification.

In [0]:
df=pd.read_csv("Bank.csv")

In [5]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
#preprocessing
x=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [7]:
x.shape

(10000, 10)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
#Encoding the catogorical variable
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X1=LabelEncoder()
x[:,1]=labelencoder_X1.fit_transform(x[:,1])
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
labelencoder_X2=LabelEncoder()
x[:,2]=labelencoder_X1.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer([('Geography',OneHotEncoder(),[1])],remainder='passthrough')
x=transformer.fit_transform(x)

In [0]:
x=x[:,1:]

In [13]:
x[:,1]

array([0.0, 1.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)

In [0]:
#splitiing the dataset into the Training set and test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
#feautre scaling important for deep learning
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
X_train.shape

(8000, 11)

In [17]:
#Part 2
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
#initializing the ANN
classifier=Sequential()

In [19]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [20]:
#Adding the second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [21]:
#Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation="sigmoid"))


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#compiling the ANN
#optimizer= adma is function that is give u gradient decent approach and it will reduce the error
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [23]:
X_train.shape

(8000, 11)

In [24]:
y_train.shape

(8000,)

In [25]:
#fitting the ANN to the training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4833 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4240 - accuracy: 0.8149
Epoch 3/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4183 - accuracy: 0.8270
Epoch 4/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4136 - accuracy: 0.8289
Epoch 5/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4103 - accuracy: 0.8303
Epoch 6/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4076 - accuracy: 0.8330
Epoch 7/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4052 - accuracy: 0.8316
Epoch 8/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4036 - accuracy: 0.8325
Epoch 9/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4020 - accuracy: 0.8322
Epoch 10/100
8000/8000 [==============================]

In [0]:
#part 3- making the prediction and evaluating the model
#predicting the test set results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [0]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [28]:
cm

array([[1505,   90],
       [ 194,  211]])

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.858